---
version: '2.3'

services:
  elastic:
    image: elasticsearch:7.9.2
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
    environment:
      node.name: es
      cluster.initial_master_nodes: es
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.9.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
volumes:
  esdata:
    driver: local

